name: yuki-no

on:
  schedule:
    - cron: "0 0 6 * *" # Every 6th day of the month
  workflow_dispatch: # Manual trigger

jobs:
  yuki-no:
    runs-on: ubuntu-latest
    steps:
      - uses: Gumball12/yuki-no@v1
        with:
          # GitHub token for authentication
          access-token: ${{ secrets.GITHUB_TOKEN }}

          # Upstream repository configuration
          head-repo: https://github.com/vuejs/docs

          # REQUIRED: Set this to a recent commit hash from vitejs/vite
          # Yuki-no will only track commits after this hash.
          # Using an old commit hash will cause the initial action run to be very slow
          # as it processes each historical commit.
          # (Subsequent runs are faster as they skip previously processed commits.)
          track-from: b70003ec17ae9a0921e5d188548ba63b834dca03 # Replace with a recent commit hash from vitejs/vite
